In [8]:
from getConfig import getConfig
import pandas as pd

In [9]:
config = getConfig()
df = pd.read_csv(config["dataLoc"]+"summary.csv")

In [10]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [11]:
print("Lowest Error rate was: ", df["error"].min())

Lowest Error rate was:  0.016

##### We captured both the AICC and the MAPE. Either one can perform best at a given time series so test them both

In [12]:
topCount = 25
lowestError = df.sort_values(by=["error"], ascending=True)[:topCount]
lowestAICC = df.sort_values(by=["aicc"], ascending=True)[:topCount]

In [13]:
print("{:>22}{:>15}".format("AICC", "Error"))
for x in ["alpha", "beta", "gamma"]:
    print("{:<15}{:<15.3f}{:.3f}".format(x, lowestAICC[x].mean(), lowestError[x].mean() ))

                  AICC          Error
alpha          0.940          0.800
beta           0.740          0.752
gamma          0.500          0.500

In [14]:
df.sort_values("aicc")[:topCount]

,trend,damped,seasonal,periods,BoxCox,bias,alpha,beta,gamma,aicc,error
26,None,False,None,99,True,False,1.000,0.700,0.500,190.350,0.017
24,None,False,None,99,True,False,1.000,0.500,0.500,190.350,0.017
25,None,False,None,99,True,False,1.000,0.600,0.500,190.350,0.017
27,None,False,None,99,True,False,1.000,0.800,0.500,190.350,0.017
28,None,False,None,99,True,False,1.000,0.900,0.500,190.350,0.017
29,None,False,None,99,True,False,1.000,1.000,0.500,190.350,0.017
35,None,False,None,99,True,False,1.100,1.000,0.500,190.390,0.017
31,None,False,None,99,True,False,1.100,0.600,0.500,190.390,0.017
32,None,False,None,99,True,False,1.100,0.700,0.500,190.390,0.017
33,None,False,None,99,True,False,1.100,0.800,0.500,190.390,0.017
30,None,False,None,99,True,False,1.100,0.500,0.500,190.390,0.017
34,None,False,None,99,True,False,1.100,0.900,0.500,190.390,0.017
18,None,False,None,99,True,False,0.900,0.500,0.500,190.520,0.017
23,None,False,None,99,True,False,0.900,1.000,0.500,190.520,0.017
22,None,False,None,99,True,False,0.900,0.900,0.500,190.520,0.017
21,None,False,None,99,True,False,0.900,0.800,0.500,190.520,0.017
20,None,False,None,99,True,False,0.900,0.700,0.500,190.520,0.017
19,None,False,None,99,True,False,0.900,0.600,0.500,190.520,0.017
17,None,False,None,99,True,False,0.800,1.000,0.500,191.130,0.016
15,None,False,None,99,True,False,0.800,0.800,0.500,191.130,0.016
14,None,False,None,99,True,False,0.800,0.700,0.500,191.130,0.016
13,None,False,None,99,True,False,0.800,0.600,0.500,191.130,0.016
12,None,False,None,99,True,False,0.800,0.500,0.500,191.130,0.016
16,None,False,None,99,True,False,0.800,0.900,0.500,191.130,0.016
6,None,False,None,99,True,False,0.700,0.500,0.500,192.070,0.016

In [15]:
df.corr()

         damped  periods  BoxCox  bias  alpha   beta  gamma   aicc  error
damped      nan      nan     nan   nan    nan    nan    nan    nan    nan
periods     nan      nan     nan   nan    nan    nan    nan    nan    nan
BoxCox      nan      nan     nan   nan    nan    nan    nan    nan    nan
bias        nan      nan     nan   nan    nan    nan    nan    nan    nan
alpha       nan      nan     nan   nan  1.000 -0.000    nan -0.911  0.878
beta        nan      nan     nan   nan -0.000  1.000    nan  0.000 -0.000
gamma       nan      nan     nan   nan    nan    nan    nan    nan    nan
aicc        nan      nan     nan   nan -0.911  0.000    nan  1.000 -0.792
error       nan      nan     nan   nan  0.878 -0.000    nan -0.792  1.000